### ISSUE TITLE
Improve the GUI

### ISSUE THREAD

**Issue by hildogjr** [hildogjr/KiCost#361]
Improve the GUI:

- [ ] Synchronize the Py GUI code to the `kicost_gui_wxFormBuilder.fbp` GUI project file;
- [ ] Add a listbox to use as BOM files to open instead the combobox. Add "+", "delete" and "up" / "down" buttons as the KiCad icons;
- [ ] Add a secondary listbox or a use the above with a checklistbox (default ON to use as BOM) to, when OFF if the same that above, to use in #360. Need fix #359 first;
- [ ] Remove the "Recognized EDAs" list, depend of first fix #359;
- [ ] Fix the "About" tab: the images sizes and the "Credits" have to go to a different about dialog;
- [x] Fix the progress bar;
- [ ] Fix the "Convert to ODS" capability in the GUI;
- [ ] Enhancement at the "Configurations" tab: missing checkbox option (`show_cat_url` and others...), add some graphical element to make clear the KiCost CLI and GUI configurations group,  and more;
- [x] Shows the last fix and new (use the HISTORY file) on the GUI startup. Look for `entry==GUI_NEWS_MESSAGE_ENTRY:` in the `kicost_gui.py` to the implementation point;
- [x] Fix the 'AUTHOR.rst' read on GUI (currently it is not reading the file);
- [ ]  Open the file and list the variants into the GUI to allow the used make a graphical choose;
- [ ] Change "Convert to ODS" to "Save as .ods", use some improved extension check to also achieve this option #411.
